### ISSUE TITLE
Tiny issue

### ISSUE THREAD

**Issue by krisbam** [psychoticmeow/Something-Awful-Image-Fixes#1]
After installing the script, links that are supposed to take me to a specific post (e.g.&threadid=3683#pti26) don't work properly while loading the page. If I append it after the page is already loaded, it works fine.
Minor annoyance, but figured I'd tell you in case it's possible to fix.

**Comment by psychoticmeow** [comment]
I did a rewrite last night exactly because of this issue, would you mind [installing the code from master](https://github.com/psychoticmeow/Something-Awful-Image-Fixes/raw/master/sa-image-fixes.user.js) and giving it a test drive before I release it?

**Comment by krisbam** [comment]
Seems to work! No threads I view actually had any new posts, so I did a workaround by doing a "mark as unread" on the thread and throwing in a '&perpage=X' to view half a page. When I then jumped to "last read post" it jumped right where it should have.

**Comment by krisbam** [comment]
Alright, I can confirm that it works now :+1:
