### ISSUE TITLE
Smaller gifs with transparency break

### ISSUE THREAD

**Issue by krisbam** [psychoticmeow/Something-Awful-Image-Fixes#2]
Another issue, sorry.
Small gifs break completely and should probably just be left as .gif. Here's two different results on (almost) the same gif: http://i.imgur.com/n8sGDjQ.gif
(One flashes wildly, the other lost its transparency)

**Comment by psychoticmeow** [comment]
Thanks, can you link to the original post? Also, what browser was this in?

**Comment by krisbam** [comment]
http://forums.somethingawful.com/showthread.php?threadid=3717559#post444874895

Firefox 38.0.1 on Windows.

**Comment by psychoticmeow** [comment]
I've fixed this by adding a constraint on small videos.

Unfortunately it seems that imgur sometimes generates corrupt webm/mp4 videos from gifs, so although smaller resolution videos are now replaced with gifs, there's no guarantee that larger videos won't suffer from the same issue.

**Comment by krisbam** [comment]
Would it be possible to have a per-image toggle to get around corrupted webms or is that beyond the scope of user scripts? Either way, great work!

**Comment by psychoticmeow** [comment]
Yeah, possibly. I was thinking of adding a link below videos to the gif version, could just do this instead.

**Comment by krisbam** [comment]
That would work perfectly as a workaround.

**Comment by psychoticmeow** [comment]
Ok, I've made the change, [it's in master again](https://github.com/psychoticmeow/Something-Awful-Image-Fixes/raw/master/sa-image-fixes.user.js).

**Comment by krisbam** [comment]
Oh my. It's even seamless, that's amazing!
