### ISSUE TITLE
Flickr images not loading

### ISSUE THREAD

**Issue by buttburglar** [psychoticmeow/Something-Awful-Image-Fixes#3]
This issue was present in 1.2.0 but I didn't realize it then.

When viewing this post:

http://forums.somethingawful.com/showthread.php?threadid=2819334&userid=0&perpage=40&pagenumber=249#post445613184

The Flickr images don't load when your script is enabled, I'm pretty sure it's just because your script is adding a "_b" before the extension like so:

https://farm9.staticflickr.com/8847/17319223193_e226bd6465_c_b.jpg -doesn't work
https://farm9.staticflickr.com/8847/17319223193_e226bd6465_c.jpg -works fine

Thanks for making this script btw, firefox used to choke and die on the image heavy threads.

**Comment by psychoticmeow** [comment]
This is now fixed in the latest release, thanks for reporting it.
