### ISSUE TITLE
Image load error

### ISSUE THREAD

**Issue by robertkent87** [psychoticmeow/Something-Awful-Image-Fixes#4]
**What did you experience?**

**Where did this happen?**
http://forums.somethingawful.com/showthread.php?threadid=3100175

**What was the error?**
```Could not load image.

eyJ1cmwiOiJodHRwOi8vaW1nLndhZmZsZWltYWdlcy5jb20vMGRhMjk2YzA0NmNmMjJjYmFkZjRk
YmFkNjkxM2IzYzA5YTdkMmMzZS9kZXZpbC5naWYifQ==```

**Comment by psychoticmeow** [comment]
Sadly it's just an old waffleimages URL, which no longer exists.

```
http://img.waffleimages.com/0da296c046cf22cbadf4dbad6913b3c09a7d2c3e/devil.gif
```

**Comment by robertkent87** [comment]
That make sense. RIP waffleimages
